version: "3.8"

services:
  db:
    image: postgis/postgis:15-3.3
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=geo_dev
    ports:
      - "5436:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
